name: shelgrenphotography-sbx
favicon: null
layout_spectrum: 0.7472
typography_spectrum: 0.51677
title: Shelgren Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9f5800'
    - '#b1772f'
    - '#cea97c'
    - '#e7d5bf'
    - '#ffffff'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
