name: shelgrenphotography-sbx
favicon: null
layout_spectrum: 0.99432
typography_spectrum: 0.08366291550919414
title: Shelgren Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9f5800'
    - '#b1772f'
    - '#cea97c'
    - '#e7d5bf'
    - '#ffffff'
  brandStrength: 0.553560932399705
  lightness: 0.19503954495303333
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
